# Generated by Django 4.0.3 on 2022-07-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='project_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
